vektonnShared:
  dockerTag: 0.6.9
  kafkaBootstrapServers: kafka-broker:9092

vektonnApi:
  replicaCount: 1
  serviceHttpPort: 80
  nodeHttpPort: 30080
  containerHttpPort: 8081
  dockerImage: vektonn/api-service
  resources:
    cpu: 500m
    memory: 128Mi
    storage: 10Mi

vektonnIndexShards:
  httpPort: 8082
  dockerImage: vektonn/index-shard-service

  vektonn-index-shard: # this name is used as a corresponding k8s service name
    indexName: QuickStart.Index
    indexVersion: "1.0"
    indexShardId: SingleShard
    replicaCount: 2
#    resources:
#      limits:
#        cpu: 1000m
#        memory: 1024Mi
#        ephemeral-storage: 10Mi
#      requests:
#        cpu: 200m
#        memory: 128Mi
#        ephemeral-storage: 10Mi

  products-1-1-shard-a:
    indexName: ExampleProject.Products
    indexVersion: "1.1"
    indexShardId: ShardA
    replicaCount: 1

  products-1-1-shard-b:
    indexName: ExampleProject.Products
    indexVersion: "1.1"
    indexShardId: ShardB
    replicaCount: 1

  products-1-2-shard-a1:
    indexName: ExampleProject.Products
    indexVersion: "1.2"
    indexShardId: ShardA1
    replicaCount: 1

  products-1-2-shard-a2:
    indexName: ExampleProject.Products
    indexVersion: "1.2"
    indexShardId: ShardA2
    replicaCount: 1

  products-1-2-shard-b1:
    indexName: ExampleProject.Products
    indexVersion: "1.2"
    indexShardId: ShardB1
    replicaCount: 1

  products-1-2-shard-b2:
    indexName: ExampleProject.Products
    indexVersion: "1.2"
    indexShardId: ShardB2
    replicaCount: 1

  products-1-2-shard-c:
    indexName: ExampleProject.Products
    indexVersion: "1.2"
    indexShardId: ShardC
    replicaCount: 1

  products-by-category-1-0-shard:
    indexName: ExampleProject.Products.ByCategory
    indexVersion: "1.0"
    indexShardId: SingleShard
    replicaCount: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
        ephemeral-storage: 10Mi
      requests:
        cpu: 200m
        memory: 128Mi
        ephemeral-storage: 10Mi
