apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka.name" . }}-scripts
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
data:
  kraft-bootstrap.sh: |-
    #!/bin/bash
    set -e

    # Docker workaround: Remove check for KAFKA_ZOOKEEPER_CONNECT parameter
    sed -i '/KAFKA_ZOOKEEPER_CONNECT/d' /etc/confluent/docker/configure

    # Docker workaround: Ignore cub zk-ready
    sed -i 's/cub zk-ready/echo ignore zk-ready/' /etc/confluent/docker/ensure

    # KRaft required step: Format the storage directory with a new cluster ID
    echo "kafka-storage format --ignore-formatted --cluster-id $(kafka-storage random-uuid) --config /etc/kafka/kafka.properties" >> /etc/confluent/docker/ensure

    # Replace the current pid 1 with original entrypoint
    exec /etc/confluent/docker/run
