apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka.name" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "kafka.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kafka.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: scripts-volume
        configMap:
          name: {{ include "kafka.name" . }}-scripts
          defaultMode: 0755
      containers:
      - name: {{ .Values.kafkaHostname }}
        image: {{ .Values.kafkaDockerImageTag | quote }}
        imagePullPolicy: IfNotPresent
        command:
        - /scripts/kraft-bootstrap.sh
        volumeMounts:
        - name: scripts-volume
          readOnly: true
          subPath: kraft-bootstrap.sh
          mountPath: /scripts/kraft-bootstrap.sh
        ports:
        - name: kafka-plaintext
          protocol: TCP
          containerPort: {{ .Values.kafkaPort }}
        env:
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:{{ .Values.kafkaPort }},CONTROLLER://localhost:9093"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://{{ .Values.kafkaHostname }}:{{ .Values.kafkaPort }}"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@localhost:9093"
        - name: KAFKA_JMX_HOSTNAME
          value: "localhost"
        - name: KAFKA_JMX_PORT
          value: "9101"
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "false"
        - name: KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS
          value: "1"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_LOG_DIRS
          value: "/tmp/kraft-combined-logs"
