apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafkaHostname }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
  ports:
  - name: kafka-plaintext
    protocol: TCP
    port: {{ .Values.kafkaPort }}
    targetPort: {{ .Values.kafkaPort }}
