dataSourceId:
  name: ExampleProject.Products
  version: 1.1
indexAlgorithm:
  type: FaissIndex.IP
idAttributes: ["ProductId"]
splitAttributes: []
shardsById:
  ShardA:
    shardsByAttributeKey:
      ShopId:
        numberOfShards: 6
        shardValues: [0, 1, 2]
  ShardB:
    shardsByAttributeKey:
      ShopId:
        numberOfShards: 6
        shardValues: [3, 4, 5]
