apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vektonn.name" . }}
  labels:
    {{- include "vektonn.shared.labels" . | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "config/**.yaml" }}
{{- sha256sum $path | nindent 2 }}: |-
    # Source: {{ $path }}
{{- tpl ($.Files.Get $path) $ | nindent 4 }}
{{- end }}
