vectorDimension: 32
vectorsAreSparse: false
attributeValueTypes:
  ProductId: Guid
  ProductCategory: string
  ProductName: string
  ShopId: Guid
  ProductImageUrl: string
permanentAttributes: ["ProductId", "ProductCategory", "ShopId"]
